import assert from 'node:assert/strict';
import test from 'node:test';
import { createNodeTaskCenterMiddleware, rhinoTaskCenterPage } from '../dist/index.js';

test('Task Center page is self-contained and points at the owner API', () => {
  const page = rhinoTaskCenterPage({ apiPath: '/api/tasks', title: '<My tasks>' });
  assert.match(page, /\/api\/tasks/);
  assert.match(page, /&lt;My tasks&gt;/);
  assert.doesNotMatch(page, /https?:\/\//);
  assert.match(page, /uncertain/);
  assert.match(page, /EventSource/);
  assert.match(page, /_events/);
  assert.match(page, /Polling fallback/);
  assert.match(page, /rhinoq-skeleton/);
  assert.match(page, /Finished/);
  assert.match(page, /Not finished/);
  assert.match(page, /aria-live="polite"/);
  assert.match(page, /aria-busy="true"/);
  assert.match(page, /The result still needs confirmation/);
  assert.match(page, /Next:/);
  assert.match(page, /function progressText/);
  assert.match(page, /New async work will appear here automatically/);
  assert.match(page, /Search tasks/);
  assert.match(page, /Needs attention/);
  assert.match(page, /Recently updated/);
  assert.match(page, /function visibleTasks/);
  assert.match(page, /history\.replaceState/);
  assert.match(page, /No tasks match this view/);
  assert.match(page, /Not independently verified yet/);
  assert.match(page, /function artifactSection/);
  assert.match(page, /verifications\?limit=20/);
  assert.match(page, /artifacts\?limit=100/);
  assert.match(page, /artifactSection\(task\)/);
  assert.match(page, /Open artifact/);
  assert.match(page, /configure secure download/);
  assert.match(page, /Load more attempts/);
  assert.match(page, /function attemptRow/);
  assert.match(page, /Requests and approvals/);
  assert.match(page, /Approval requested/);
  assert.match(page, /resolutionId/);
  assert.match(page, /function waitpointSection/);
  const script = page.match(/<script>([\s\S]*)<\/script>/)?.[1];
  assert.ok(script);
  assert.doesNotThrow(() => new Function(script));
});

test('Task Center middleware serves its list and one owner-facing detail route', () => {
  const middleware = createNodeTaskCenterMiddleware({ path: '/my/tasks', apiPath: '/tasks', navigation: { overviewPath: '/', workbenchPath: '/admin' } });
  const response = { headers: {}, setHeader(name, value) { this.headers[name] = value; }, end(body) { this.body = body; } };
  middleware({ method: 'GET', url: '/my/tasks', headers: {} }, response);
  assert.equal(response.statusCode, 200);
  assert.match(response.body, /<!doctype html>/);
  assert.match(response.body, /Overview/);
  assert.match(response.body, /View details/);
  const detail = { headers: {}, setHeader(name, value) { this.headers[name] = value; }, end(body) { this.body = body; } };
  middleware({ method: 'GET', url: '/my/tasks/task-1', headers: {} }, detail);
  assert.equal(detail.statusCode, 200);
  assert.match(detail.body, /Attempts/);
  let passed = false;
  middleware({ method: 'POST', url: '/my/tasks', headers: {} }, {}, () => { passed = true; });
  assert.equal(passed, true);
  let nestedPassed = false;
  middleware({ method: 'GET', url: '/my/tasks/task-1/unknown', headers: {} }, {}, () => { nestedPassed = true; });
  assert.equal(nestedPassed, true);
});
