package correlation

import (
	"errors"
	"strings"
)

// Trace context is the missing half of correlation.
//
// The rest of this package answers "which system ran this, against which
// business subject". It does not answer "where does this sit in the request
// that started it". That gap is what makes a failed Task expensive to
// investigate: RhinoQ can show its own attempts and evidence, but an operator
// still has to guess which trace in their APM is the same unit of work, and
// guessing is done by comparing timestamps by hand.
//
// RhinoQ therefore carries W3C Trace Context rather than inventing an id. The
// standard is deliberate on two points that matter here:
//
//   - it is a header contract, not a runtime. Accepting traceparent costs one
//     parse and one column; it does not pull in an SDK, an exporter or a
//     background flush loop, so the engine keeps its dependency budget.
//   - the id is generated by whoever starts the request. RhinoQ is downstream
//     of an HTTP handler in every adoption path it targets, so a trace almost
//     always already exists. Minting a new one would produce an id that
//     correlates with nothing.
//
// What RhinoQ stores is therefore the incoming context, verbatim. It is
// evidence about the caller, held to the same standard as the rest of the
// ledger: recorded when presented, absent when not, never inferred.
const (
	// TraceParentHeader and TraceStateHeader are the W3C header names. They are
	// lowercase because the specification writes them that way; Go's
	// http.Header canonicalises on access, so this is for documentation and for
	// the SDK contract rather than for lookup.
	TraceParentHeader = "traceparent"
	TraceStateHeader  = "tracestate"

	// traceVersion00 is the only version whose field layout is fixed. A higher
	// version must still be parsed for its first four fields and its extra
	// fields ignored, which is what the specification requires of a receiver
	// that wants to keep working after the standard grows.
	traceVersion00 = "00"

	traceIDHexLen = 32
	spanIDHexLen  = 16
	traceFlagsLen = 2
	// traceParent00Len is 2 + 1 + 32 + 1 + 16 + 1 + 2.
	traceParent00Len = 55

	MaxTraceStateBytes = 512

	// flagSampled is the only flag bit the standard defines. RhinoQ records it
	// but never acts on it: dropping evidence because an upstream sampler said
	// so would mean the Tasks least likely to be traced are the ones RhinoQ
	// explains worst.
	flagSampled = 0x01
)

var (
	ErrTraceParentMalformed = errors.New("traceparent is not a valid W3C trace context")
	ErrTraceStateBounds     = errors.New("tracestate exceeds its length bound")
)

// TraceContext is one incoming W3C trace context.
//
// The zero value means the caller presented none, which is a normal and common
// state: a Task enqueued by a cron tick or a CLI command has no inbound
// request. Code must treat absence as absence and not substitute a fresh id.
type TraceContext struct {
	// TraceID is the 32-hex-character id shared by every span in the trace. It
	// is the join key an operator pastes into their APM.
	TraceID string
	// SpanID is the caller's span, the parent of any span RhinoQ work would
	// create. Named SpanID rather than the specification's "parent-id" because
	// that is what it is called everywhere it is consumed.
	SpanID string
	// Flags is the raw two-hex-character flag byte, kept verbatim so a future
	// flag survives a round trip through RhinoQ instead of being silently
	// dropped to zero.
	Flags string
	// TraceState is the vendor list, kept opaque. RhinoQ has no reason to
	// interpret another vendor's entries and every reason to pass them through
	// unmodified.
	TraceState string
}

func (t TraceContext) Zero() bool {
	return t.TraceID == "" && t.SpanID == ""
}

// Sampled reports the upstream sampling decision. It is exposed for display,
// not for control flow inside RhinoQ.
func (t TraceContext) Sampled() bool {
	flags, ok := decodeHexByte(t.Flags)
	return ok && flags&flagSampled != 0
}

// TraceParent renders the header value. An empty context renders empty rather
// than a syntactically valid all-zero parent, because a downstream service must
// be able to tell "no trace" from "a trace whose ids are zero"; the latter is
// what the specification calls invalid.
func (t TraceContext) TraceParent() string {
	if t.Zero() {
		return ""
	}
	flags := t.Flags
	if flags == "" {
		flags = "00"
	}
	return traceVersion00 + "-" + t.TraceID + "-" + t.SpanID + "-" + flags
}

// ParseTraceParent reads a traceparent header value.
//
// It is strict on the parts that carry meaning and forgiving on the part that
// is allowed to grow. An unparseable header is reported as an error so a caller
// can decide, but every caller in RhinoQ treats it the same way: drop it and
// continue. A malformed trace header is not a reason to fail a Task, and a
// request that would otherwise succeed must not start failing because an
// upstream proxy corrupted a diagnostic field.
func ParseTraceParent(raw string) (TraceContext, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return TraceContext{}, ErrTraceParentMalformed
	}
	fields := strings.Split(value, "-")
	if len(fields) < 4 {
		return TraceContext{}, ErrTraceParentMalformed
	}
	version, traceID, spanID, flags := fields[0], fields[1], fields[2], fields[3]

	// Version ff is reserved as invalid by the specification, and a version
	// that is not two hex characters is not a version at all.
	if len(version) != 2 || !isLowerHex(version) || version == "ff" {
		return TraceContext{}, ErrTraceParentMalformed
	}
	// Version 00 fixes the total length. Rejecting a longer string here is what
	// stops a v00 header with trailing junk from being read as if the junk were
	// a future field.
	if version == traceVersion00 && len(value) != traceParent00Len {
		return TraceContext{}, ErrTraceParentMalformed
	}
	if len(traceID) != traceIDHexLen || !isLowerHex(traceID) || isAllZero(traceID) {
		return TraceContext{}, ErrTraceParentMalformed
	}
	if len(spanID) != spanIDHexLen || !isLowerHex(spanID) || isAllZero(spanID) {
		return TraceContext{}, ErrTraceParentMalformed
	}
	if len(flags) != traceFlagsLen || !isLowerHex(flags) {
		return TraceContext{}, ErrTraceParentMalformed
	}
	return TraceContext{TraceID: traceID, SpanID: spanID, Flags: flags}, nil
}

// WithTraceState attaches the vendor list after bounds checking. It is separate
// from parsing because a valid traceparent with an oversized tracestate is
// still useful: the join key is the part an investigation needs.
func (t TraceContext) WithTraceState(raw string) (TraceContext, error) {
	state := strings.TrimSpace(raw)
	if state == "" {
		t.TraceState = ""
		return t, nil
	}
	if len(state) > MaxTraceStateBytes {
		return t, ErrTraceStateBounds
	}
	t.TraceState = state
	return t, nil
}

// Normalize returns the context with a canonical flag field, so a value that
// was constructed in code rather than parsed is stored the same way a parsed one
// is.
func (t TraceContext) Normalize() (TraceContext, error) {
	if t.Zero() {
		return TraceContext{}, nil
	}
	parsed, err := ParseTraceParent(t.TraceParent())
	if err != nil {
		return TraceContext{}, err
	}
	return parsed.WithTraceState(t.TraceState)
}

func isLowerHex(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i]
		if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return len(s) > 0
}

func isAllZero(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] != '0' {
			return false
		}
	}
	return len(s) > 0
}

func decodeHexByte(s string) (byte, bool) {
	if len(s) != 2 || !isLowerHex(s) {
		return 0, false
	}
	return hexNibble(s[0])<<4 | hexNibble(s[1]), true
}

func hexNibble(c byte) byte {
	if c >= 'a' {
		return c - 'a' + 10
	}
	return c - '0'
}
